export const browserCoreExamples = [
  "opuncleh browser status",
  "opuncleh browser start",
  "opuncleh browser stop",
  "opuncleh browser tabs",
  "opuncleh browser open https://example.com",
  "opuncleh browser focus abcd1234",
  "opuncleh browser close abcd1234",
  "opuncleh browser screenshot",
  "opuncleh browser screenshot --full-page",
  "opuncleh browser screenshot --ref 12",
  "opuncleh browser snapshot",
  "opuncleh browser snapshot --format aria --limit 200",
  "opuncleh browser snapshot --efficient",
  "opuncleh browser snapshot --labels",
];

export const browserActionExamples = [
  "opuncleh browser navigate https://example.com",
  "opuncleh browser resize 1280 720",
  "opuncleh browser click 12 --double",
  'opuncleh browser type 23 "hello" --submit',
  "opuncleh browser press Enter",
  "opuncleh browser hover 44",
  "opuncleh browser drag 10 11",
  "opuncleh browser select 9 OptionA OptionB",
  "opuncleh browser upload /tmp/opuncleh/uploads/file.pdf",
  'opuncleh browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "opuncleh browser dialog --accept",
  'opuncleh browser wait --text "Done"',
  "opuncleh browser evaluate --fn '(el) => el.textContent' --ref 7",
  "opuncleh browser console --level error",
  "opuncleh browser pdf",
];
